### ISSUE TITLE
lowerCaseTest in unittests stuck

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/soot-infoflow#20]
Hi:

The lowerCaseTest in StringTests stucks and will not terminate. I found useTaintWrapper is false, is this the reason?

**Comment by StevenArzt** [comment]
All these tests run fine on our nightly build server. However, some of them require more memory than available in the default configuration of the JVM. We thus run our nightly test suite with -Xmx4g which makes the whole suite finish in very reasonable time. Have you tried increasing the Java heap size?

**Comment by StevenArzt** [comment]
I close this issue since there has not been any further activity for quite a while. It works on our nightly build system, so there shouldn't be a general issue.
