### ISSUE TITLE
Printing trace from sink to source

### ISSUE THREAD

**Issue by ahmet-celik** [secure-software-engineering/soot-infoflow#26]
The current output does not seem to include the entire trace from source to sink. Is there a way to retrieve such a trace? For instance in the following example, we'd want the following trace from sink to source: `3->2->5->4->2->1`.

```
main () {
1:  y = source()
2:  x = foo(y,'true')
3:  sink(x)
}

foo ( y , b) {
4: if(b) {
5:     return y
6: } else {
7:     return 0
8:  }
}
```

**Comment by ericbodden** [comment]
FlowDroid only collects abstractions along one witness.
So the trace will not be complete (will not include conditionals, etc.)
 
If you want to reconstruct the trace, you can either do it from the FlowDroid trace and the ICFG as an extra post-computation,
or you can collect a full witness during the IFDS propagation using the same technique as in FlowTwist (section 3.1 of this paper: http://www.bodden.de/pubs/lhbm14flowtwist.pdf ). If you go for this solution, you would have to modify your FlowAbstraction, and the propagate function of the solver. Then, you should be able to reconstruct the traces. The advantage of this method is that you would have all paths from one source to a sink, and not just one witness like FlowDroid reports.

**Comment by ahmet-celik** [comment]
Thank you for the quick reply. 
In principle, we probably would be happy with a trace that includes all intermediate method invocations. For instance, in the example `main->foo->main` would be sufficient. Would this also require major changes or is this easy to extract from the FlowDroid trace?
For instance, could we easily get the caller of method foo on the trace instead of all potential callers?

**Comment by StevenArzt** [comment]
Actually, FlowDroid can also be configured to give you all traces instead of just one witness. This is, however, inherently an exponential set. Assume that you have n conditionals along the path. Then, there are O(2^n) possibilities to build a path. Generating all of them is usually too much and doesn't scale.

The method invocations should all be contained inside the witness regardless of whether you configure FlowDroid to get one witness (the default) or enumerate them akll. The only statements that are missing from the traces are those that do not influence the taint state as such, i.e., conditionals along the way.

**Comment by ahmet-celik** [comment]
Thank you for the reply.
When I tried out the example from the above, I only got following output which does not any invocation of method `foo`. Is there any option to enable to see all method invocations along the path? 
Output:
```
[main] INFO soot.jimple.infoflow.Infoflow - Callgraph has 105 edges
[main] INFO soot.jimple.infoflow.Infoflow - Implicit flow tracking is NOT enabled
[main] INFO soot.jimple.infoflow.Infoflow - Exceptional flow tracking is NOT enabled
[main] INFO soot.jimple.infoflow.Infoflow - Running with a maximum access path length of 3
[main] INFO soot.jimple.infoflow.Infoflow - Using path-agnostic result collection
[main] INFO soot.jimple.infoflow.Infoflow - Recursive access path shortening is enabled
[main] INFO soot.jimple.infoflow.Infoflow - Looking for sources and sinks...
[main] INFO soot.jimple.infoflow.Infoflow - Source lookup done, found 2 sources and 1 sinks.
[main] INFO soot.jimple.infoflow.Infoflow - Taint wrapper hits: 0
[main] INFO soot.jimple.infoflow.Infoflow - Taint wrapper misses: 22
[main] INFO soot.jimple.infoflow.Infoflow - IFDS problem with 60 forward and 4 backward edges solved, processing 1 results...
[main] INFO soot.jimple.infoflow.data.pathBuilders.ContextSensitivePathBuilder - Context-sensitive path reconstructor started
[main] INFO soot.jimple.infoflow.data.pathBuilders.ContextSensitivePathBuilder - Obtainted 1 connections between null sources and sinks
[main] INFO soot.jimple.infoflow.data.pathBuilders.ContextSensitivePathBuilder - Building path 1
[main] INFO soot.jimple.infoflow.data.pathBuilders.ContextSensitivePathBuilder - Path processing took 0.004613929 seconds in total
[main] INFO soot.jimple.infoflow.Infoflow - The sink staticinvoke <Test: void sink(java.lang.Object)>($r4) in method <Test: void main(java.lang.String[])> was called with values from the following sources:
[main] INFO soot.jimple.infoflow.Infoflow - - $r2 = staticinvoke <Test: java.lang.Object source(java.lang.Object)>($r1) in method <Test: void main(java.lang.String[])>
[main] INFO soot.jimple.infoflow.Infoflow - 	on Path: 
[main] INFO soot.jimple.infoflow.Infoflow - 	 -> <Test: void main(java.lang.String[])>
[main] INFO soot.jimple.infoflow.Infoflow - 		 -> staticinvoke <Test: void sink(java.lang.Object)>($r4)
```

Source code of the example above:
```java
public class Test {
	public static Object source(Object o) {return o;}
	public static void sink(Object o) {}	
	public static int foo(int y,boolean b) {
		if(b)
			return y;
		else
			return 0;
	}
	
	public static void main(String[] args) {
		int y = (int) source(42);
		int x = foo(y, true);
		sink(x);
	}
}
```

**Comment by StevenArzt** [comment]
In your output, you didn't get a real path, but just the source and sink methods. To get a real path, you need to enable this feature first. Try "--pathalgo contextsensitive" on the command-line.

**Comment by ahmet-celik** [comment]
Thank you very much. Now, I'm be able to get paths.
