### ISSUE TITLE
Private "results" in SerializedInfoflowResults

### ISSUE THREAD

**Issue by thomasbrueggemann** [secure-software-engineering/soot-infoflow#39]
Hi there,

is there a reason why the `results ` member is private in SerializedInfoflowResults.java?
 
https://github.com/secure-software-engineering/soot-infoflow/blob/develop/src/soot/jimple/infoflow/results/xml/SerializedInfoflowResults.java#L18

It would be great to access the MultiMap after reading in an XML file.
I could easily create a pull request, but want to check back with you if this is intended.

**Comment by StevenArzt** [comment]
I added a getter method. Thanks for the hint!
