### ISSUE TITLE
 No sources found, aborting analysis

### ISSUE THREAD

**Issue by benben2301** [secure-software-engineering/soot-infoflow#40]
Dear Steven Arzt,
I use the newest version, but it cannot find sources. But if I use old version, everything goes well. The apk and SourcesAndSinks.txt are same.  Do I forget any new options? 
Thanks,
Hua

**Comment by StevenArzt** [comment]
Hi Hua,

Have you double-checked that your sources are actually reachable inside your APK? The newer versions should be more precise in checking whether sources can actually be triggered. If the source should be reachable, please send the APK file and the SourcesAndSinks.txt file to Steven.Arzt@sit.fraunhofer.de and I'll have a look.

Best regards,
  Steven

**Comment by StevenArzt** [comment]
The source is found on my machine. There was, however, a bug in how field overwrites were treated, which lead to no results being found. I have fixed the issue and my output now looks like this:

```
Found a flow to sink specialinvoke $r0.<com.example.guanhua.android_test.MainActivity: void sink(int)>($i0), from the following sources:
	- $i1 = specialinvoke $r0.<com.example.guanhua.android_test.MainActivity: int source()>() (in <com.example.guanhua.android_test.MainActivity: void mainLogic()>)
```

**Comment by benben2301** [comment]
Why it cannot print whole path? It seems source.getPath() returns null in this case. 

Thanks and best regards,
Hua

**Comment by benben2301** [comment]
I found the answer, the default PathBuilder is  ContextInsensitiveSourceFinder, now I change it to ContextSensitive, it works fine now.

Thanks a lot,
Guanhua
