### ISSUE TITLE
how to find all paths from source to sink

### ISSUE THREAD

**Issue by benben2301** [secure-software-engineering/soot-infoflow#41]
@StevenArzt ,
Hi!
I found that flowdroid can only find one path from one source to sink, even there are more than one paths between the source and the sink (for example,  "if branch" in the path).  

In the old version, I found there was a "bug" that it uses source and sink (instead of whole found path) to generate hash code for determining whether the found path is a new path. As a consequence, it cannot collect more than one paths between specific source and sink in the result set. I find this issue should be solved during I read the code of this version. But the result shows that it still can only collect one path.

So is it possible to find all paths from source to sink by using flowdroid?

Best regards,
Hua

**Comment by benben2301** [comment]
I found, this is a bug in soot.jimple.infoflow.results.ResultSourceInfo.java
`	public int hashCode() {
		return (path != null && !InfoflowConfiguration.getPathAgnosticResults() ? 31 * this.path.hashCode() : 0)
				+ (pathAPs != null && !InfoflowConfiguration.getPathAgnosticResults() ? 31 * this.pathAPs.hashCode() : 0)
				+ (InfoflowConfiguration.getOneResultPerAccessPath() ?
						31 * this.accessPath.hashCode() : 0)
				+ 7 * (this.source == null ? 0 : this.source.hashCode());
	}`

It should be 
`	public int hashCode() {
		return (path != null && !InfoflowConfiguration.getPathAgnosticResults() ? 31 * this.path.hashCode() : 0)
				+ (pathAPs != null && !InfoflowConfiguration.getPathAgnosticResults() ? 31 * this.pathAPs.hashCode() : 0)
				+ (InfoflowConfiguration.getOneResultPerAccessPath() ?
						0: 31 * this.accessPath.hashCode() )
				+ 7 * (this.source == null ? 0 : this.source.hashCode());
	}`

**Comment by benben2301** [comment]
The issue #37 is related to this bug.

Thanks,
Hua

**Comment by StevenArzt** [comment]
This is not a bug, this is a feature. By default, FlowDroid will report only a single path per source-to-sink connection. If you want to enumerate all paths, you have to set InfoflowConfigure.PathAgnosticResults to "false". However, note that the number of paths is exponential in the number of branching statement along the path, so reconstructing all of them will usually not scale for examples that are larger than a handful of lines of code. That's also why the option is disabled by default.

**Comment by benben2301** [comment]
Yes, sorry that I misunderstood "oneResultPerAccessPath". 
Thanks,
Hua
