### ISSUE TITLE
Hardcoded numThreads in ContextInsensitiveSourceFinder

### ISSUE THREAD

**Issue by dfbravo** [secure-software-engineering/soot-infoflow#48]
The class is soot.jimple.infoflow.data.pathBuilders.ContextInsensitiveSourceFinder.

Here is a snippet of code with a 1 hardcoded for numThreads. Is this intentional? The other path builder classes actually use numThreads.

``` java
    private CountingThreadPoolExecutor createExecutor(int numThreads) {
        return new CountingThreadPoolExecutor
                (1/*numThreads*/, Integer.MAX_VALUE, 30, TimeUnit.SECONDS,
                new LinkedBlockingQueue<Runnable>());
    }
```

@StevenArzt

**Comment by StevenArzt** [comment]
Thanks for reporting the issue. The class has been refactored in the meantime and the problem has been resolved.
