### ISSUE TITLE
Purpose of "EndSummary" and "Incoming"

### ISSUE THREAD

**Issue by nfsp3k** [secure-software-engineering/soot-infoflow#50]
While I develop a backward analysis tool by using soot and soot-infoflow,
I want to know what the purpose of "EndSummary" and "Incoming" is.

What I understand is as following:
In processCall() of IFDSSolver.java, it calls getReturnFlowFunction after adding "Incoming" and getting "endSummary". Then, it propagates newly tainted abstractions.

In processExit() of IFDSSolver.java, it also calls getReturnFlowFunction after adding "endSummary" and getting "Incoming". It propagates newly tainted abstractions too.

I think they are redundant works. They look same logic to me. 
What is the reason why calling getReturnFlowFunction() in both processCall() and processExit() and
why using "endSummary" and "incoming"?

I believe your answer will be very helpful to me.

**Comment by ericbodden** [comment]
@nfsp3k Sorry about the late response.
It's not redundant, there are two different things happening. First consider processCall(). The point is that IFDS stores procedure summary at the side of the callee (!) procedure. Now assume we are processing a call to a procedure that has been summarized already. In this processCall() must do the following:

1. compute the call-flow function into the callee
1. apply the summary for the callee-side input (which becomes also part of the incoming-set)
1. compute the return-flow function to map the summary back into the caller's context

during processExit() we are propagating stuff when a procedure has been computed and thus summarized for the first time. At this point we install/store a summary and also map back the summarized information into the caller's context. You will find the same kind of duplication also in Reps' original IFDS paper.
