### ISSUE TITLE
What's the meaning of excludeList here?

### ISSUE THREAD

**Issue by pengzhendong** [secure-software-engineering/soot-infoflow#53]
``` java
public EasyTaintWrapper(File f) throws IOException{
    ...
    List<String> excludeList = new LinkedList<String>();
    while(line != null){
        if (!line.isEmpty() && !line.startsWith("%"))
            if (line.startsWith("~"))
                excludeList.add(line.substring(1));
            line = reader.readLine();
    }
    this.excludeList = SootMethodRepresentationParser.v().parseClassNames(excludeList, true);
    logger.info("Loaded wrapper entries for {} classes and {} exclusions.", classList.size(), excludeList.size());
    ...
}
```

I think it should print `this.excludeList.size()` instead of `excludeList.size()`, right?
Does `<java.util.List: java.util.Iterator iterator()>()` in EasyTaintWrapperSource.txt not belong to any list? It can't match by regex because of `>()` in methodList.
If yes, please give me the honor to pull a request, thanks.

**Comment by StevenArzt** [comment]
The entry in the EasyTaintWrapperSource.txt file was indeed wrong. I have fixed the issue.
