### ISSUE TITLE
NPE in Infoflow.runAnalysis() when using SetupApplication.constructCallGraph()

### ISSUE THREAD

**Issue by mbenz89** [secure-software-engineering/soot-infoflow#55]
When using the new _constructCallGraph()_ method of Flowdroid 2.0, an NPE occurs in _InfoFlow.runAnalysis()_ when trying to initialize a nulled SourceSinksManager ([code](https://github.com/secure-software-engineering/soot-infoflow/blob/develop/src/soot/jimple/infoflow/Infoflow.java#L254)).

This might go unnoticed since the call graph is generated beforehand and the exception is caught in _runAnalysis()_. Though, code optimizations like dead code analysis and constant propagation can never be executed in this case.

**Comment by StevenArzt** [comment]
That's indeed a bug. Thanks for reporting, I have fixed it.
