### ISSUE TITLE
Possible copy-paste error in ImplicitFlowAliasStrategy

### ISSUE THREAD

**Issue by gabriel-fallen** [secure-software-engineering/soot-infoflow#64]
https://github.com/secure-software-engineering/soot-infoflow/blob/develop/src/soot/jimple/infoflow/aliasing/ImplicitFlowAliasStrategy.java#L84

Shouldn't it be
```
mapRight.add(apLeft);
```
?

**Comment by StevenArzt** [comment]
It should indeed. Thanks for pointing that out, I'll commit a fix.
